# Change these first
owner: Fachpersonal # Your GitHub username
repo: uptime_ubload # Your GitHub repository name

# Add your sites here
sites:
  - name: Ubload.space Homepage
    url: https://www.ubload.space
  - name: Ubload.space uploaded Images
    url: https://www.ubload.space/uploads/1614268604.png

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.ubload.space
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://www.ubload.space/images/header.webp
  name: Ubload.Space | Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: Back to ubload.space
      href: https://www.ubload.space

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
